version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "18080:8000"   # <-- usa 18080 en tu máquina

  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "18501:8501"   # <-- usa 18501 en tu máquina
    environment:
      - API_URL=http://api:8000
    depends_on:
      - api
